

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Diplom_Beloborodov.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class user24Entities : DbContext
{
    public user24Entities()
        : base("name=user24Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Authorizations> Authorizations { get; set; }

    public virtual DbSet<Fakts> Fakts { get; set; }

    public virtual DbSet<Newss> Newss { get; set; }

    public virtual DbSet<Oznacomlenie> Oznacomlenie { get; set; }

    public virtual DbSet<StartLocation> StartLocation { get; set; }

}

}

