
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Diplom_Beloborodov.Models
{

using System;
    using System.Collections.Generic;
    
public partial class StartLocation
{

    public int Id { get; set; }

    public int Oznakomlenie { get; set; }

    public int Fakt { get; set; }

    public int News { get; set; }

    public int IdAuth { get; set; }



    public virtual Authorizations Authorizations { get; set; }

    public virtual Fakts Fakts { get; set; }

    public virtual Newss Newss { get; set; }

    public virtual Oznacomlenie Oznacomlenie { get; set; }

}

}
